version: '3.1'

services:
  mysql:
    image: mysql:8.0.23
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usersdb
    ports:
      - "3306:3306"

#  docker run --name mysql -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=usersdb -p 3306:3306 -d mysql:8.0.23
